* cl-webnovel-to-org
*** _DevMort_

This project aims to scrape a web novel from a link and get the contents into a single org file.

What you do with that org file is up to you. Whether to convert it into a PDF or an EPUB file (with you own costumizations).

** Installation
1. Put the directory on =/path/to/quicklisp/local-projects=.
2. Run =make= and put the resulting =cl-webnovel-to-org= binary somewhere on $PATH.

** Usage
*** SBCL
1. Put the directory on =/path/to/quicklisp/local-projects=.
2. Load the project with =sbcl= and run:
#+begin_src bash
  > (ql:quickload :cl-webnovel-to-org)
  > (setup)
#+end_src
*** Using the binary
1. =make install=
2. Run in terminal: =cl-webnovel-to-org=.

** Recommended Sites
Choose one from [[https://fmhy.pages.dev/readingpiracyguide/#light-novel-sites][here]]. _Don't use sites that have cloudflare_.

** FAQ
*** What do I put into the tags?
1. Inspect Element > Go to button, text content, or title > right click > copy > css selector
2. Paste that on the question on =(setup)=.
*** It suddenly failed?
a. Check the last chapter it failed on, see if there's some new "gimmick" on the page.
b. You were cloudflared.
_Find another site._
   
** License
    Converts a web novel into an org file.
    Copyright (C) 2023 DevMort

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see [[https://www.gnu.org/licenses/]].

